# -*- coding: utf-8 -*-
"""Spam Email Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAQO6BJErsEIgexGGxsBb6dg9bf3lBHR
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('emails.csv')

df.shape

df.head()

df['spam'].value_counts()

# Remove the duplicates
df.drop_duplicates(inplace=True)

df.shape

df['spam'].value_counts()

df.isnull().sum()

df

"""## Make the data X and Y"""

x_data = df.text.values

data = pd.DataFrame(x_data, columns=['Text data'])

data

y_data = df.text.values

"""## Split the dataset"""

import sklearn

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.25, random_state=42)

"""## Data preprocessing"""

from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()

x_train_count = count_vectorizer.fit_transform(x_train)

x_train_count.toarray()

"""## Train and Test model"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model_fit = model.fit(x_train_count, y_train)

x_test_count = count_vectorizer.transform(x_test)

x_test_count.toarray()

